version = 1

test_patterns = [
  "tests/*/test_*.py"
]

exclude_patterns = [
  "src/pip/_vendor/**"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "req.txt"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
